/*
 * @Author: mulingyuer
 * @Date: 2025-10-22 11:35:03
 * @LastEditTime: 2025-10-29 17:38:47
 * @LastEditors: mulingyuer
 * @Description: 示例数据
 * @FilePath: \frontend\src\views\index-tts2\components\ExampleDrawer\example-data.ts
 * 怎么可能会有bug！！！
 */
import type { ExampleData } from "../../types";

export const EXAMPLE_DATA: ExampleData = [
	{
		isExpert: false,
		do_sample: true,
		emo_control_method: 0,
		emo_random: false,
		emo_ref_path: "",
		emo_weight: 1,
		length_penalty: 0,
		max_mel_tokens: 1500,
		max_text_tokens_per_segment: 120,
		num_beams: 3,
		prompt: "",
		repetition_penalty: 10,
		spk_audio_prompt: "voice_01.wav",
		temperature: 0.8,
		text: "Translate for me, what is a surprise!",
		top_k: 30,
		top_p: 0.8,
		vec1: 0,
		vec2: 0,
		vec3: 0,
		vec4: 0,
		vec5: 0,
		vec6: 0,
		vec7: 0,
		vec8: 0
	},
	{
		isExpert: false,
		do_sample: true,
		emo_control_method: 0,
		emo_random: false,
		emo_ref_path: "",
		emo_weight: 1,
		length_penalty: 0,
		max_mel_tokens: 1500,
		max_text_tokens_per_segment: 120,
		num_beams: 3,
		prompt: "",
		repetition_penalty: 10,
		spk_audio_prompt: "voice_02.wav",
		temperature: 0.8,
		text: "The palace is strict, no false rumors, Lady Qi!",
		top_k: 30,
		top_p: 0.8,
		vec1: 0,
		vec2: 0,
		vec3: 0,
		vec4: 0,
		vec5: 0,
		vec6: 0,
		vec7: 0,
		vec8: 0
	},
	{
		isExpert: false,
		do_sample: true,
		emo_control_method: 0,
		emo_random: false,
		emo_ref_path: "",
		emo_weight: 1,
		length_penalty: 0,
		max_mel_tokens: 1500,
		max_text_tokens_per_segment: 120,
		num_beams: 3,
		prompt: "",
		repetition_penalty: 10,
		spk_audio_prompt: "voice_03.wav",
		temperature: 0.8,
		text: "这个呀，就是我们精心制作准备的纪念品，大家可以看到这个色泽和这个材质啊，哎呀多么的光彩照人。",
		top_k: 30,
		top_p: 0.8,
		vec1: 0,
		vec2: 0,
		vec3: 0,
		vec4: 0,
		vec5: 0,
		vec6: 0,
		vec7: 0,
		vec8: 0
	},
	{
		isExpert: false,
		do_sample: true,
		emo_control_method: 0,
		emo_random: false,
		emo_ref_path: "",
		emo_weight: 1,
		length_penalty: 0,
		max_mel_tokens: 1500,
		max_text_tokens_per_segment: 120,
		num_beams: 3,
		prompt: "",
		repetition_penalty: 10,
		spk_audio_prompt: "voice_04.wav",
		temperature: 0.8,
		text: "你就需要我这种专业人士的帮助，就像手无缚鸡之力的人进入雪山狩猎，一定需要最老练的猎人指导。",
		top_k: 30,
		top_p: 0.8,
		vec1: 0,
		vec2: 0,
		vec3: 0,
		vec4: 0,
		vec5: 0,
		vec6: 0,
		vec7: 0,
		vec8: 0
	},
	{
		isExpert: false,
		do_sample: true,
		emo_control_method: 0,
		emo_random: false,
		emo_ref_path: "",
		emo_weight: 1,
		length_penalty: 0,
		max_mel_tokens: 1500,
		max_text_tokens_per_segment: 120,
		num_beams: 3,
		prompt: "",
		repetition_penalty: 10,
		spk_audio_prompt: "voice_05.wav",
		temperature: 0.8,
		text: "在真正的日本剑道中，格斗过程极其短暂，常常短至半秒，最长也不超过两秒，利剑相击的转瞬间，已有一方倒在血泊中。但在这电光石火的对决之前，双方都要以一个石雕般凝固的姿势站定，长时间的逼视对方，这一过程可能长达十分钟！",
		top_k: 30,
		top_p: 0.8,
		vec1: 0,
		vec2: 0,
		vec3: 0,
		vec4: 0,
		vec5: 0,
		vec6: 0,
		vec7: 0,
		vec8: 0
	},
	{
		isExpert: false,
		do_sample: true,
		emo_control_method: 0,
		emo_random: false,
		emo_ref_path: "",
		emo_weight: 1,
		length_penalty: 0,
		max_mel_tokens: 1500,
		max_text_tokens_per_segment: 120,
		num_beams: 3,
		prompt: "",
		repetition_penalty: 10,
		spk_audio_prompt: "voice_06.wav",
		temperature: 0.8,
		text: "今天呢，咱们开一部新书，叫《赛博朋克二零七七》。这词儿我听着都新鲜。这赛博朋克啊，简单理解就是“高科技，低生活”。这一听，我就明白了，于老师就爱用那高科技的东西，手机都得拿脚纹开，大冬天为了解锁脱得一丝不挂，冻得跟王八蛋似的。",
		top_k: 30,
		top_p: 0.8,
		vec1: 0,
		vec2: 0,
		vec3: 0,
		vec4: 0,
		vec5: 0,
		vec6: 0,
		vec7: 0,
		vec8: 0
	},
	{
		isExpert: false,
		do_sample: true,
		emo_control_method: 1,
		emo_random: false,
		emo_ref_path: "emo_sad.wav",
		emo_weight: 1,
		length_penalty: 0,
		max_mel_tokens: 1500,
		max_text_tokens_per_segment: 120,
		num_beams: 3,
		prompt: "",
		repetition_penalty: 10,
		spk_audio_prompt: "voice_07.wav",
		temperature: 0.8,
		text: "酒楼丧尽天良，开始借机竞拍房间，哎，一群蠢货。",
		top_k: 30,
		top_p: 0.8,
		vec1: 0,
		vec2: 0,
		vec3: 0,
		vec4: 0,
		vec5: 0,
		vec6: 0,
		vec7: 0,
		vec8: 0
	},
	{
		isExpert: false,
		do_sample: true,
		emo_control_method: 1,
		emo_random: false,
		emo_ref_path: "emo_hate.wav",
		emo_weight: 1,
		length_penalty: 0,
		max_mel_tokens: 1500,
		max_text_tokens_per_segment: 120,
		num_beams: 3,
		prompt: "",
		repetition_penalty: 10,
		spk_audio_prompt: "voice_08.wav",
		temperature: 0.8,
		text: "你看看你，对我还有没有一点父子之间的信任了。",
		top_k: 30,
		top_p: 0.8,
		vec1: 0,
		vec2: 0,
		vec3: 0,
		vec4: 0,
		vec5: 0,
		vec6: 0,
		vec7: 0,
		vec8: 0
	},
	{
		isExpert: false,
		do_sample: true,
		emo_control_method: 2,
		emo_random: false,
		emo_ref_path: "",
		emo_weight: 1,
		length_penalty: 0,
		max_mel_tokens: 1500,
		max_text_tokens_per_segment: 120,
		num_beams: 3,
		prompt: "",
		repetition_penalty: 10,
		spk_audio_prompt: "voice_09.wav",
		temperature: 0.8,
		text: "对不起嘛！我的记性真的不太好，但是和你在一起的事情，我都会努力记住的~",
		top_k: 30,
		top_p: 0.8,
		vec1: 0,
		vec2: 0,
		vec3: 0.8,
		vec4: 0,
		vec5: 0,
		vec6: 0,
		vec7: 0,
		vec8: 0
	},
	{
		isExpert: false,
		do_sample: true,
		emo_control_method: 2,
		emo_random: false,
		emo_ref_path: "",
		emo_weight: 1,
		length_penalty: 0,
		max_mel_tokens: 1500,
		max_text_tokens_per_segment: 120,
		num_beams: 3,
		prompt: "",
		repetition_penalty: 10,
		spk_audio_prompt: "voice_10.wav",
		temperature: 0.8,
		text: "哇塞！这个爆率也太高了！欧皇附体了！",
		top_k: 30,
		top_p: 0.8,
		vec1: 0,
		vec2: 0,
		vec3: 0,
		vec4: 0,
		vec5: 0,
		vec6: 0,
		vec7: 1,
		vec8: 0
	}
];
